export * from './default'
export * from './default-centered'
export * from './image-right-detached-title'
export * from './image-right'
export * from './image-left'
export * from './call-to-action'
export * from './email-signup'
export * from './photo-gallery'
export * from './form-right'

// customs that can be reused
export * from './featured-products'
export * from './default-hero'
export * from './our-team' // this is team in flux
export * from './accordion'
export * from './video-right'
export * from './thank-you'

// customs for american covers
export * from './hero-centered-with-bg-image'
export * from './why-choose-us'
export * from './affiliations'
export * from './hero-safety-get-a-quote-form'
export * from './image-right-with-svg'
export * from './feature-list'
export * from './message'
export * from './hero-left-with-bg-image'
export * from './hero-centered-form'
export * from './benefit-list'
export * from './hero-contact-form-right'
export * from './default-left-get-a-quote-form'
export * from './hero-left-get-a-quote-form'
export * from './feature-list-with-svg'
export * from './applications'
export * from './form-right-get-a-quote-form'
export * from './specifications'
export * from './policy'